### ISSUE TITLE
Does not work with Azure Dev Ops 2019

### ISSUE THREAD

**Issue by horvatic** [onlyutkarsh/ExportAsPDF#7]
This should work with Azure DevOps Services, but it seems to just crash. No pop up

**Comment by huntantr** [comment]
Does not work in TFS2017 or TFS2018 either. Nothing happens when clicking on the menu item.

**Comment by horvatic** [comment]
@onlyutkarsh assuming this repo is dead?

**Comment by onlyutkarsh** [comment]
@horvatic unfortunately yes. I no longer maintain this extension. The product and SDK I think has moved a lot, which basically means this needs to be rewritten.

**Comment by horvatic** [comment]
@onlyutkarsh Its all good! Can you please make this repo read only, and update the docs for the plugin. I can see you getting this message a lot!
